version: '3'
services:
  humble-desktop-full:
    image: johnny555/stc:v1.01
    user: ros
    volumes:
      - ../:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl

    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER

    command: /bin/sh -c "while sleep 1000; do :; done"
